### PR TITLE
Asyncify the specs

### PR DESCRIPTION
**Pull request by Arcanemagus**
Bring in `jasmine-fix` to allow the use of `async`/`await` in the specs and refactor them to take advantage of this.

### CODE REVIEW

**Comment by Arcanemagus** [comment]
This being impossible to debug on Windows makes this very difficult to work on.... as far as I can tell from the debug statements `codeclimate` is somehow taking over 10 seconds to return, so the specs just give up on it and fail.

**Comment by Arcanemagus** [comment]
As there isn't really much point in bringing this in for just the `beforeEach` block, and it looks like the actual test can't be (easily) run with `async`, I'm just going to close this PR for now.

**Comment by Arcanemagus** [comment]
Anyone that's able to run this locally want to check on why this isn't working? The CI build isn't even printing the debug text...

**Comment by cgalvarez** [comment]
I'm currently having problems with the tests on #83 , so I'm trying to fix them with your approach here.

@Arcanemagus I cannot get your debug messages printed too, so I've used another approach: writing a log file. I've checked that in my case, I'm getting `messages = null`, so I suspect that's what happening to you here, and that's why the CI build fails with `TypeError: Cannot read property 'length' of null`.

Keep on digging into this, but any help would be greatly appreciated :wink:

**Comment by cgalvarez** [comment]
Finally got to understand this weird behavior.

When running specs, [no timeout is provided to `Helpers.exec(...)`](https://github.com/AtomLinter/linter-codeclimate/blob/master/lib/index.js#L185), so after the @Arcanemagus ' [mythical 10s](https://github.com/AtomLinter/linter-codeclimate/pull/65#issuecomment-331267783) :stuck_out_tongue: the cli is killed and `null` is returned.

I'm fixing this issue in #83 too, since I need it to get tests passing.

**Pull request closed without merging**
