### PR TITLE
Rewrite in ES2017

### PR DESCRIPTION
**Pull request by Arcanemagus**
Rewrite the linter in ES2017 code, including the following changes:

* Use Helpers.rangeFromLineNumber() to generate ranges for incomplete positions, this will use the regex for the current language to highlight the next "word" automatically.
* Move to the Performance API for measuring time. Times are only logged to the console in Developer mode now.
* Move the setting to a `configSchema` in the `package.json` so Atom doesn't have to execute the code to read the settings.
* Utilize `async`/`await` where possible

### CODE REVIEW

**Comment by Arcanemagus** [comment]
@maxjacobson You'll probably want to fix the Code Climate config, as I only know enough to cut out the `coffeelint` part 😛.

**Comment by maxjacobson** [comment]
Happy to re-enable eslint after this is merged

**Comment by Arcanemagus** [comment]
Whoops, looks like this got dropped. Looking into finishing this up.

**Comment by Arcanemagus** [comment]
There we go, passing build!

**Pull request merged**
